default_platform(:ios)

platform :ios do
  
  desc "Run all tests"
  lane :test do
    run_tests(
      scheme: "TestBCA",
      device: "iPhone 15",
      clean: true,
      code_coverage: true,
      output_directory: "./test_output",
      output_types: "html,junit"
    )
  end
  
  desc "Run only unit tests"
  lane :unit_tests do
    run_tests(
      scheme: "TestBCA",
      device: "iPhone 15",
      only_testing: ["TestBCATests"],
      clean: true
    )
  end
  
  desc "Run only UI tests"
  lane :ui_tests do
    run_tests(
      scheme: "TestBCA", 
      device: "iPhone 15",
      only_testing: ["TestBCAUITests"],
      clean: true
    )
  end
  
  desc "Build for testing"
  lane :build_for_testing do
    setup_ci(force: true)
    build_app(
      scheme: "TestBCA",
      configuration: "Debug",
      build_for_testing: true,
      skip_archive: true,
      skip_codesigning: true
    )
  end
  
  desc "Lint code"
  lane :lint do
    swiftlint(
      mode: :lint,
      reporter: "github-actions-logging",
      config_file: ".swiftlint.yml"
    )
  end
  
  
  desc "Full CI pipeline"
  lane :ci do
    lint
    test
    
  end
  
end

