name: CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-14
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
        
    - name: Run Tests
      run: |
        xcodebuild test \
          -scheme "TestBCA" \
          -destination "platform=iOS Simulator,name=iPhone 15,OS=17.2" \
          -enableCodeCoverage YES
