name: CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-14
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
        
    - name: Cache SPM
      uses: actions/cache@v4
      with:
        path: |
          .build
          ~/Library/Developer/Xcode/DerivedData/**/SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.swift', '**/*.pbxproj') }}
        
    - name: Clean and Build
      run: |
        xcodebuild clean \
          -scheme "TestBCA"
          
        xcodebuild build-for-testing \
          -scheme "TestBCA" \
          -destination "platform=iOS Simulator,name=iPhone 15,OS=17.2" \
          -derivedDataPath DerivedData
          
    - name: Run Tests
      run: |
        xcodebuild test-without-building \
          -scheme "TestBCA" \
          -destination "platform=iOS Simulator,name=iPhone 15,OS=17.2" \
          -derivedDataPath DerivedData \
          -enableCodeCoverage YES
